name: nextflow_dkl_demo
channels:
  - conda-forge
  - defaults

dependencies:
  # Python dependencies
  - python=3.11
  - matplotlib
  - numpy<2.0
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - rpy2
  - openblas
  - lapack
  - gfortran
  - scikit-learn
  - scipy
  - seaborn
  - pyyaml
  - joblib
  - hdf5
  - h5py
  # R dependencies
  - conda-forge::r-base
  - conda-forge::r-robustgasp
  - conda-forge::r-hdf5r
  - conda-forge::r-optparse
  - conda-forge::r-jsonlite
  - conda-forge::r-essentials
  - conda-forge::r-argparse
  # Pip dependencies
  - pip
  - pip:
      - -r requirements.txt
